version: 2
updates:
  - package-ecosystem: "gomod"
    commit-message:
      prefix: "deps:"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "12:00"
  - package-ecosystem: "github-actions"
    commit-message:
      prefix: "deps:"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "12:00"
